Tul 199/citace pro iframe in item view
HuynhKhoa1601/dspace-angular pull request #5
Opened 2023-06-05 13:06 UTC by HuynhKhoa1601

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description
https://github.com/dataquest-dev/dspace-angular/issues/199

2023-06-06 10:30 UTC, milanmajchrak requested changes

2023-06-06 10:30 UTC, milanmajchrak commented on src/app/core/shared/tul/constants.ts
> +export const CITACE_PRO_BASE_URL = 'https://www.citacepro.com/api/dspace/citace/oai';
This is only reminder: this constants will be retrieved from BE (clarin-dspace.cfg)

2023-06-06 10:30 UTC, milanmajchrak commented on src/app/item-page/simple/field-components/specific-field/citation/item-page-citation.component.spec.ts
> +  const mockHandle = '15240/151431';
Is it a real handle? I think for test purposes we should better use some fake data :)

2023-06-06 10:30 UTC, milanmajchrak commented on src/app/item-page/simple/field-components/specific-field/citation/item-page-citation.component.ts
> +import {CITACE_PRO_BASE_URL, UNIVERSITY_USING_DSPACE} from '../../../../../core/shared/tul/constants';
empty space is missing in the brackets

2023-06-06 10:36 UTC, milanmajchrak commented
@HuynhKhoa1601 Please move this iframe CitacePRO component into this component body: 
![image](https://github.com/HuynhKhoa1601/dspace-angular/assets/90026355/7645456f-31d8-49fe-a1c1-34aedae69d09)

2023-06-06 12:53 UTC, HuynhKhoa1601 commented
thanks I'll update it

2023-06-06 12:53 UTC, milanmajchrak commented
@HuynhKhoa1601 Please add this <ds-item-page-citation-field [handle]="object?.handle"></ds-item-page-citation-field> component into `src/app/item-page/simple/item-types/publication/publication.component.html` also. Because it won't be seen in the publication.

2023-06-12 06:39 UTC, milanmajchrak approved these changes

2023-06-12 06:39 UTC, merged